name: Publish on CurseForge

on:
  workflow_dispatch:

env:
  RELEASE_TYPE: release
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_APITOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
#    environment: curseforge_apiToken
    steps:
      - name: Check CURSEFORGE_APITOKEN Length
        run: |
          SECRET_LENGTH=$(echo -n "${{ secrets.CURSEFORGE_APITOKEN }}" | wc -m)
          echo "CURSEFORGE_APITOKEN length: $SECRET_LENGTH"
          if [ "$SECRET_LENGTH" -eq 0 ]; then
            echo "CURSEFORGE_APITOKEN is empty!"
            exit 1
          fi

      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "microsoft"
          java-version: 25

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Set Release Name Environment Variable
        id: set_release_name
        run: |
          RELEASE_NAME=$(basename $(ls build/libs/*.jar | grep -v sources))
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Publish (CurseForge)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
#          modrinth-id: ecliptic-seasons-fabricated
#          modrinth-featured: true
#          modrinth-unfeature-mode: subset
#          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
#          curseforge-id: 1514738
#          curseforge-token: "${{ env.CURSEFORGE_TOKEN }}"
          version-type: "${{ env.RELEASE_TYPE }}"
          changelog-file: changelog.md
          loaders: fabric
          game-versions: |
            [26.2,26.3)
          dependencies: ""
          name: "${{env.RELEASE_NAME}}"
          files: |
            build/libs/${{ env.RELEASE_NAME }}
